# Generated by Django 3.1.2 on 2020-11-03 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(max_length=50, verbose_name='Miejscowość')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='Czas odbioru')),
                ('pick_up_comment', models.TextField(verbose_name='Komentarz do odbioru')),
                ('categories', models.ManyToManyField(to='mysite.Category', verbose_name='Kategorie')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.institution', verbose_name='Instytucja')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
