# Generated by Django 3.1.2 on 2020-11-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Liczba worków'),
        ),
    ]
