# Generated by Django 3.1.2 on 2020-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20201103_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
    ]
