# Generated by Django 3.1.2 on 2020-11-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_donation_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='categories',
        ),
        migrations.AddField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mysite.institution', verbose_name='Instytucja'),
            preserve_default=False,
        ),
    ]
