# Generated by Django 3.1.2 on 2020-11-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20201103_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='mysite.Category', verbose_name='Kategorie'),
        ),
    ]
