# Generated by Django 3.1.2 on 2020-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20201114_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
    ]
