# Generated by Django 3.1.2 on 2020-11-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20201114_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='type',
            new_name='institutionType',
        ),
    ]
